version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules  
    ports:
    - 5000:5000
    command: npm run start
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:13
    env_file:
      - .env 
    environment:
      PG_DATA: /var/lib/postgresql/
       POSTGRES_PASSWORD=postgres
    ports:
    - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/
    restart: always

volumes: 
  pgdata: